### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by aPissarek** [Polewska/webapp22-Polewska#6]
I have uploaded the design models for your app. Please confirm or let me know if something is not to your liking.

**Comment by aPissarek** [comment]
Actually, calling it "sex" was not really a mistake. The sex is the physical or biological classification into male/female. However, for legal reasons, nowadays, it is safer to also add a third option for political correctness. The term for the sex you identify with (as opposed to the biological one) is gender. So essentially I only changed this to be on the safe side legally.

Yes, good point, I will change the property name to gender as well. Thank you.

**Comment by Polewska** [comment]
I have noticed you changed the property name and it now looks perfect. I'm officially conforming this design for our future app. 
Thank you for your hard work 👍
